spring:
  application:
    name: smarttask-pro
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/smarttask}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:U21hcnRUYXNrUHJvU2VjcmV0S2V5MjAyNFN1cGVyU2VjdXJlQmFzZTY0RW5jb2RlZEtleUZvckpXVA==}
    expiration: 86400000 # 1 day in ms

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
